const Dogs = [
    {
        id: 1,
        name: 'Brauni',
        gender: 'male',
        ageDigit: 0.8,
        ageText: 'year',
        puppy: true,
        weight_will_be: '25 kg',
        breed: 'large',
        typeOfHair: 'smooth',
        img: 'img/brauni-1.PNG',
    },
    {
        id: 2,
        name: 'Malysh',
        gender: 'male',
        ageDigit: 0.3,
        ageText: 'year',
        puppy: true,
        weight_will_be: '10 kg',
        breed: 'medium',
        typeOfHair: 'smooth',
        img: 'img/malysh-1.PNG',
    },
    {
        id: 3,
        name: 'Miia',
        gender: 'female',
        ageDigit: 0.3,
        ageText: 'year',
        puppy: true,
        weight_will_be: '10 kg',
        breed: 'medium',
        typeOfHair: 'smooth',
        img: 'img/mia-1.PNG',
    },
    {
        id: 4,
        name: 'Mimi',
        gender: 'female',
        ageDigit: 0.3,
        ageText: 'year',
        puppy: true,
        weight_will_be: '15 kg',
        breed: 'medium',
        typeOfHair: 'smooth',
        img: 'img/mimi-1.PNG',
    },
    {
        id: 5,
        name: 'Pusha',
        gender: 'female',
        ageDigit: 2,
        ageText: 'years',
        puppy: false,
        weight_will_be: '15 kg',
        breed: 'medium',
        typeOfHair: 'shaggy',
        img: 'img/pusha-1.PNG',
    },
    {
        id: 6,
        name: 'Knopa',
        gender: 'female',
        ageDigit: 1.5,
        ageText: 'years',
        puppy: false,
        weight_will_be: '15 kg',
        breed: 'medium',
        typeOfHair: 'smooth',
        img: 'img/knopa-1.PNG',
    },
    {
        id: 7,
        name: 'Molli',
        gender: 'female',
        ageDigit: 0.4,
        ageText: 'year',
        puppy: true,
        weight_will_be: '15 kg',
        breed: 'medium',
        typeOfHair: 'smooth',
        img: 'img/molli-1.PNG',
    },
    {
        id: 8,
        name: 'Slyvka',
        gender: 'female',
        ageDigit: 3,
        ageText: 'years',
        puppy: false,
        weight_will_be: '7 kg',
        breed: 'small',
        typeOfHair: 'shaggy',
        img: 'img/slyvka-1.PNG',
    },
    {
        id: 9,
        name: 'Zaichyk',
        gender: 'male',
        ageDigit: 1.5,
        ageText: 'years',
        puppy: false,
        weight_will_be: '30 kg',
        breed: 'large',
        typeOfHair: 'smooth',
        img: 'img/zaichyk-1.PNG',
    },
]

export default Dogs;